"""empty message

Revision ID: 4214461f0b7c
Revises: 598342783de9
Create Date: 2021-12-22 18:58:11.885830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4214461f0b7c'
down_revision = '598342783de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'archive')
    # ### end Alembic commands ###
